// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.33.1
// source: proto/goindex/goindex.proto

package goindex

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	GoIndexService_ListModules_FullMethodName = "/goindex.GoIndexService/ListModules"
	GoIndexService_GetModule_FullMethodName   = "/goindex.GoIndexService/GetModule"
	GoIndexService_AddModule_FullMethodName   = "/goindex.GoIndexService/AddModule"
)

// GoIndexServiceClient is the client API for GoIndexService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// The Go package index service.
type GoIndexServiceClient interface {
	// List all indexed modules.
	ListModules(ctx context.Context, in *ListModulesRequest, opts ...grpc.CallOption) (*ListModulesResponse, error)
	// Get a specific module by path and version.
	GetModule(ctx context.Context, in *GetModuleRequest, opts ...grpc.CallOption) (*Module, error)
	// Add a module to the index.
	AddModule(ctx context.Context, in *AddModuleRequest, opts ...grpc.CallOption) (*AddModuleResponse, error)
}

type goIndexServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewGoIndexServiceClient(cc grpc.ClientConnInterface) GoIndexServiceClient {
	return &goIndexServiceClient{cc}
}

func (c *goIndexServiceClient) ListModules(ctx context.Context, in *ListModulesRequest, opts ...grpc.CallOption) (*ListModulesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListModulesResponse)
	err := c.cc.Invoke(ctx, GoIndexService_ListModules_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *goIndexServiceClient) GetModule(ctx context.Context, in *GetModuleRequest, opts ...grpc.CallOption) (*Module, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Module)
	err := c.cc.Invoke(ctx, GoIndexService_GetModule_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *goIndexServiceClient) AddModule(ctx context.Context, in *AddModuleRequest, opts ...grpc.CallOption) (*AddModuleResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AddModuleResponse)
	err := c.cc.Invoke(ctx, GoIndexService_AddModule_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GoIndexServiceServer is the server API for GoIndexService service.
// All implementations must embed UnimplementedGoIndexServiceServer
// for forward compatibility.
//
// The Go package index service.
type GoIndexServiceServer interface {
	// List all indexed modules.
	ListModules(context.Context, *ListModulesRequest) (*ListModulesResponse, error)
	// Get a specific module by path and version.
	GetModule(context.Context, *GetModuleRequest) (*Module, error)
	// Add a module to the index.
	AddModule(context.Context, *AddModuleRequest) (*AddModuleResponse, error)
	mustEmbedUnimplementedGoIndexServiceServer()
}

// UnimplementedGoIndexServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedGoIndexServiceServer struct{}

func (UnimplementedGoIndexServiceServer) ListModules(context.Context, *ListModulesRequest) (*ListModulesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListModules not implemented")
}
func (UnimplementedGoIndexServiceServer) GetModule(context.Context, *GetModuleRequest) (*Module, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetModule not implemented")
}
func (UnimplementedGoIndexServiceServer) AddModule(context.Context, *AddModuleRequest) (*AddModuleResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddModule not implemented")
}
func (UnimplementedGoIndexServiceServer) mustEmbedUnimplementedGoIndexServiceServer() {}
func (UnimplementedGoIndexServiceServer) testEmbeddedByValue()                        {}

// UnsafeGoIndexServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to GoIndexServiceServer will
// result in compilation errors.
type UnsafeGoIndexServiceServer interface {
	mustEmbedUnimplementedGoIndexServiceServer()
}

func RegisterGoIndexServiceServer(s grpc.ServiceRegistrar, srv GoIndexServiceServer) {
	// If the following call pancis, it indicates UnimplementedGoIndexServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&GoIndexService_ServiceDesc, srv)
}

func _GoIndexService_ListModules_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListModulesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GoIndexServiceServer).ListModules(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GoIndexService_ListModules_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GoIndexServiceServer).ListModules(ctx, req.(*ListModulesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GoIndexService_GetModule_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetModuleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GoIndexServiceServer).GetModule(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GoIndexService_GetModule_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GoIndexServiceServer).GetModule(ctx, req.(*GetModuleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GoIndexService_AddModule_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddModuleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GoIndexServiceServer).AddModule(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GoIndexService_AddModule_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GoIndexServiceServer).AddModule(ctx, req.(*AddModuleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// GoIndexService_ServiceDesc is the grpc.ServiceDesc for GoIndexService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var GoIndexService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "goindex.GoIndexService",
	HandlerType: (*GoIndexServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListModules",
			Handler:    _GoIndexService_ListModules_Handler,
		},
		{
			MethodName: "GetModule",
			Handler:    _GoIndexService_GetModule_Handler,
		},
		{
			MethodName: "AddModule",
			Handler:    _GoIndexService_AddModule_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/goindex/goindex.proto",
}
