// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.1
// source: proto/goindex/goindex.proto

package goindex

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// A Go module entry from the Go module index.
type Module struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	Version       string                 `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Module) Reset() {
	*x = Module{}
	mi := &file_proto_goindex_goindex_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Module) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Module) ProtoMessage() {}

func (x *Module) ProtoReflect() protoreflect.Message {
	mi := &file_proto_goindex_goindex_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Module.ProtoReflect.Descriptor instead.
func (*Module) Descriptor() ([]byte, []int) {
	return file_proto_goindex_goindex_proto_rawDescGZIP(), []int{0}
}

func (x *Module) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *Module) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *Module) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

// A collection of modules.
type ModuleList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Modules       []*Module              `protobuf:"bytes,1,rep,name=modules,proto3" json:"modules,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ModuleList) Reset() {
	*x = ModuleList{}
	mi := &file_proto_goindex_goindex_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ModuleList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ModuleList) ProtoMessage() {}

func (x *ModuleList) ProtoReflect() protoreflect.Message {
	mi := &file_proto_goindex_goindex_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ModuleList.ProtoReflect.Descriptor instead.
func (*ModuleList) Descriptor() ([]byte, []int) {
	return file_proto_goindex_goindex_proto_rawDescGZIP(), []int{1}
}

func (x *ModuleList) GetModules() []*Module {
	if x != nil {
		return x.Modules
	}
	return nil
}

// Request to list indexed modules.
type ListModulesRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Maximum number of modules to return. 0 means no limit.
	Limit int32 `protobuf:"varint,1,opt,name=limit,proto3" json:"limit,omitempty"`
	// Filter by module path prefix.
	PathPrefix    string `protobuf:"bytes,2,opt,name=path_prefix,json=pathPrefix,proto3" json:"path_prefix,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListModulesRequest) Reset() {
	*x = ListModulesRequest{}
	mi := &file_proto_goindex_goindex_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListModulesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListModulesRequest) ProtoMessage() {}

func (x *ListModulesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_goindex_goindex_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListModulesRequest.ProtoReflect.Descriptor instead.
func (*ListModulesRequest) Descriptor() ([]byte, []int) {
	return file_proto_goindex_goindex_proto_rawDescGZIP(), []int{2}
}

func (x *ListModulesRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ListModulesRequest) GetPathPrefix() string {
	if x != nil {
		return x.PathPrefix
	}
	return ""
}

// Response containing indexed modules.
type ListModulesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Modules       []*Module              `protobuf:"bytes,1,rep,name=modules,proto3" json:"modules,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListModulesResponse) Reset() {
	*x = ListModulesResponse{}
	mi := &file_proto_goindex_goindex_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListModulesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListModulesResponse) ProtoMessage() {}

func (x *ListModulesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_goindex_goindex_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListModulesResponse.ProtoReflect.Descriptor instead.
func (*ListModulesResponse) Descriptor() ([]byte, []int) {
	return file_proto_goindex_goindex_proto_rawDescGZIP(), []int{3}
}

func (x *ListModulesResponse) GetModules() []*Module {
	if x != nil {
		return x.Modules
	}
	return nil
}

// Request to get a specific module.
type GetModuleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	Version       string                 `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetModuleRequest) Reset() {
	*x = GetModuleRequest{}
	mi := &file_proto_goindex_goindex_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetModuleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetModuleRequest) ProtoMessage() {}

func (x *GetModuleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_goindex_goindex_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetModuleRequest.ProtoReflect.Descriptor instead.
func (*GetModuleRequest) Descriptor() ([]byte, []int) {
	return file_proto_goindex_goindex_proto_rawDescGZIP(), []int{4}
}

func (x *GetModuleRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *GetModuleRequest) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

// Request to add a module to the index.
type AddModuleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Module        *Module                `protobuf:"bytes,1,opt,name=module,proto3" json:"module,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddModuleRequest) Reset() {
	*x = AddModuleRequest{}
	mi := &file_proto_goindex_goindex_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddModuleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddModuleRequest) ProtoMessage() {}

func (x *AddModuleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_goindex_goindex_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddModuleRequest.ProtoReflect.Descriptor instead.
func (*AddModuleRequest) Descriptor() ([]byte, []int) {
	return file_proto_goindex_goindex_proto_rawDescGZIP(), []int{5}
}

func (x *AddModuleRequest) GetModule() *Module {
	if x != nil {
		return x.Module
	}
	return nil
}

// Response after adding a module.
type AddModuleResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Module        *Module                `protobuf:"bytes,1,opt,name=module,proto3" json:"module,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddModuleResponse) Reset() {
	*x = AddModuleResponse{}
	mi := &file_proto_goindex_goindex_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddModuleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddModuleResponse) ProtoMessage() {}

func (x *AddModuleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_goindex_goindex_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddModuleResponse.ProtoReflect.Descriptor instead.
func (*AddModuleResponse) Descriptor() ([]byte, []int) {
	return file_proto_goindex_goindex_proto_rawDescGZIP(), []int{6}
}

func (x *AddModuleResponse) GetModule() *Module {
	if x != nil {
		return x.Module
	}
	return nil
}

var File_proto_goindex_goindex_proto protoreflect.FileDescriptor

const file_proto_goindex_goindex_proto_rawDesc = "" +
	"\n" +
	"\x1bproto/goindex/goindex.proto\x12\agoindex\x1a\x1fgoogle/protobuf/timestamp.proto\"p\n" +
	"\x06Module\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\x128\n" +
	"\ttimestamp\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\"7\n" +
	"\n" +
	"ModuleList\x12)\n" +
	"\amodules\x18\x01 \x03(\v2\x0f.goindex.ModuleR\amodules\"K\n" +
	"\x12ListModulesRequest\x12\x14\n" +
	"\x05limit\x18\x01 \x01(\x05R\x05limit\x12\x1f\n" +
	"\vpath_prefix\x18\x02 \x01(\tR\n" +
	"pathPrefix\"@\n" +
	"\x13ListModulesResponse\x12)\n" +
	"\amodules\x18\x01 \x03(\v2\x0f.goindex.ModuleR\amodules\"@\n" +
	"\x10GetModuleRequest\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\";\n" +
	"\x10AddModuleRequest\x12'\n" +
	"\x06module\x18\x01 \x01(\v2\x0f.goindex.ModuleR\x06module\"<\n" +
	"\x11AddModuleResponse\x12'\n" +
	"\x06module\x18\x01 \x01(\v2\x0f.goindex.ModuleR\x06module2\xd7\x01\n" +
	"\x0eGoIndexService\x12H\n" +
	"\vListModules\x12\x1b.goindex.ListModulesRequest\x1a\x1c.goindex.ListModulesResponse\x127\n" +
	"\tGetModule\x12\x19.goindex.GetModuleRequest\x1a\x0f.goindex.Module\x12B\n" +
	"\tAddModule\x12\x19.goindex.AddModuleRequest\x1a\x1a.goindex.AddModuleResponseB(Z&github.com/fred/go_index/proto/goindexb\x06proto3"

var (
	file_proto_goindex_goindex_proto_rawDescOnce sync.Once
	file_proto_goindex_goindex_proto_rawDescData []byte
)

func file_proto_goindex_goindex_proto_rawDescGZIP() []byte {
	file_proto_goindex_goindex_proto_rawDescOnce.Do(func() {
		file_proto_goindex_goindex_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_goindex_goindex_proto_rawDesc), len(file_proto_goindex_goindex_proto_rawDesc)))
	})
	return file_proto_goindex_goindex_proto_rawDescData
}

var file_proto_goindex_goindex_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_proto_goindex_goindex_proto_goTypes = []any{
	(*Module)(nil),                // 0: goindex.Module
	(*ModuleList)(nil),            // 1: goindex.ModuleList
	(*ListModulesRequest)(nil),    // 2: goindex.ListModulesRequest
	(*ListModulesResponse)(nil),   // 3: goindex.ListModulesResponse
	(*GetModuleRequest)(nil),      // 4: goindex.GetModuleRequest
	(*AddModuleRequest)(nil),      // 5: goindex.AddModuleRequest
	(*AddModuleResponse)(nil),     // 6: goindex.AddModuleResponse
	(*timestamppb.Timestamp)(nil), // 7: google.protobuf.Timestamp
}
var file_proto_goindex_goindex_proto_depIdxs = []int32{
	7, // 0: goindex.Module.timestamp:type_name -> google.protobuf.Timestamp
	0, // 1: goindex.ModuleList.modules:type_name -> goindex.Module
	0, // 2: goindex.ListModulesResponse.modules:type_name -> goindex.Module
	0, // 3: goindex.AddModuleRequest.module:type_name -> goindex.Module
	0, // 4: goindex.AddModuleResponse.module:type_name -> goindex.Module
	2, // 5: goindex.GoIndexService.ListModules:input_type -> goindex.ListModulesRequest
	4, // 6: goindex.GoIndexService.GetModule:input_type -> goindex.GetModuleRequest
	5, // 7: goindex.GoIndexService.AddModule:input_type -> goindex.AddModuleRequest
	3, // 8: goindex.GoIndexService.ListModules:output_type -> goindex.ListModulesResponse
	0, // 9: goindex.GoIndexService.GetModule:output_type -> goindex.Module
	6, // 10: goindex.GoIndexService.AddModule:output_type -> goindex.AddModuleResponse
	8, // [8:11] is the sub-list for method output_type
	5, // [5:8] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_proto_goindex_goindex_proto_init() }
func file_proto_goindex_goindex_proto_init() {
	if File_proto_goindex_goindex_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_goindex_goindex_proto_rawDesc), len(file_proto_goindex_goindex_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_goindex_goindex_proto_goTypes,
		DependencyIndexes: file_proto_goindex_goindex_proto_depIdxs,
		MessageInfos:      file_proto_goindex_goindex_proto_msgTypes,
	}.Build()
	File_proto_goindex_goindex_proto = out.File
	file_proto_goindex_goindex_proto_goTypes = nil
	file_proto_goindex_goindex_proto_depIdxs = nil
}
